### ISSUE TITLE
`UPDATE` / `INSERT` / `FLUSH` と `SELECT` を実行するとクラッシュする

### ISSUE THREAD

**Issue by Watson1978** [mroonga/mroonga#743]
### What happend?

`UPDATE` / `INSERT` / `FLUSH` クエリーが頻繁に実行されている状態で、別のクライアントから `SELECT` で全文検索すると Mroonga がクラッシュします。

### パッケージインストール
```sh
sudo apt update
sudo apt install -y -V apt-transport-https
sudo apt install -y -V wget
sudo apt install -y -V lsb-release
wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
wget https://packages.groonga.org/debian/groonga-apt-source-latest-bookworm.deb
sudo apt install -y -V ./groonga-apt-source-latest-bookworm.deb
sudo apt update
sudo apt install -y -V mariadb-10.11-mroonga

# MariaDB のエラーログを取得するために rsyslog をインストール
sudo apt install -y -V rsyslog
# Ruby の実行環境
sudo apt install -y -V ruby ruby-dev gcc make libmariadb-dev
```

#### ログ出力先を設定
`/etc/mysql/mariadb.conf.d/50-server.cnf` を編集します。
`[mariadb]` というセクションがあるので、以下のように `log_error = /var/log/mysql/mariadb_error.log` を追加します。

```
# This group is only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]
log_error = /var/log/mysql/mariadb_error.log
```

ログが保存されるディレクトリを用意して起きます。
```
mkdir -p /var/log/mysql/
chown mysql /var/log/mysql/
```

#### データベース作成
```
systemctl start mariadb
```

```
# mysql -uroot
MariaDB [(none)]> CREATE DATABASE test;
```

## 再現コード
```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'mysql2'
  gem 'faker'
end

class Initializer
  MAX_DATA = 10000

  def run
    drop_table
    create_table
    insert_initial_data
  end

  def drop_table
    client.query("DROP TABLE IF EXISTS user;")
  end

  def create_table
    client.query(<<~SQL)
      CREATE TABLE user
      (
          id          BIGINT         PRIMARY KEY AUTO_INCREMENT,
          name        VARCHAR(255)   NOT NULL,
          age         INTEGER        NOT NULL,
          FULLTEXT INDEX (name)
      ) ENGINE = Mroonga DEFAULT CHARSET utf8;
    SQL
  end

  def insert_initial_data
    sql = "INSERT INTO user VALUES"

    MAX_DATA.times do |i|
      sql << "(#{i+1}, \"#{client.escape(Faker::Name.name)}\", #{Random.rand(80)})"
      unless i == MAX_DATA - 1
        sql << ", "
      end
    end
    sql << ";"

    client.query(sql)
  end

  def client
    @client ||= Mysql2::Client.new(
      host: "localhost",
      username: "root",
      database: "test",
    )
  end
end

class Updater
  def run
    update
    insert
    flush
  end

  def update
    sql = "UPDATE user SET name = \"#{client.escape(Faker::Name.name)}\", age = #{Random.rand(80)} WHERE id = #{Random.rand(record_count)};"
    client.query(sql)
  end

  def insert
    sql = "INSERT INTO user (name, age) VALUES(\"#{client.escape(Faker::Name.name)}\", #{Random.rand(80)});"
    client.query(sql)
  end

  def flush
    client.query("FLUSH TABLES;")
  end

  def record_count
    results = client.query("SELECT count(id) FROM user;")
    results.each do |row|
      return row["count(id)"]
    end
  end

  def client
    @client ||= Mysql2::Client.new(
      host: "localhost",
      username: "root",
      database: "test",
    )
  end
end

class Selecter
  def run
    results = client.query("SELECT * FROM user WHERE MATCH(name) AGAINST(\"+Mrs\" IN BOOLEAN MODE);")
    # results.each do |row|
    #   p row
    # end
  end

  def client
    @client ||= Mysql2::Client.new(
      host: "localhost",
      username: "root",
      database: "test",
    )
  end
end

Initializer.new.run

Thread.new do
  updater = Updater.new
  loop do
    updater.run
  end
end

Thread.new do
  selecter = Selecter.new
  loop do
    selecter.run
  end
end

sleep 60
```

## 再現手順
再現コードを実行します。

```
% ruby sql.rb 
#<Thread:0x00007bec49d8e378 sql.rb:119 run> terminated with exception (report_on_exception is true):
/var/lib/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query': Lost connection to server during query (Mysql2::Error::ConnectionError)
        from /var/lib/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query'
        from /var/lib/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt'
        from /var/lib/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query'
        from sql.rb:95:in `run'
        from sql.rb:122:in `block (2 levels) in <main>'
        from sql.rb:121:in `loop'
        from sql.rb:121:in `block in <main>'
#<Thread:0x00007bec49d8e4b8 sql.rb:112 run> terminated with exception (report_on_exception is true):
/var/lib/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query': Lost connection to server during query (Mysql2::Error::ConnectionError)
        from /var/lib/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query'
        from /var/lib/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt'
        from /var/lib/gems/3.1.0/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query'
        from sql.rb:70:in `insert'
        from sql.rb:59:in `run'
        from sql.rb:115:in `block (2 levels) in <main>'
        from sql.rb:114:in `loop'
        from sql.rb:114:in `block in <main>'
```
ある程度実行すると client の接続が切れてしまいます。

このとき `/var/log/mysql/mariadb_error.log` には以下のようなログが出力されていました。
```
2024-07-29  9:25:38 0 [Note] Starting MariaDB 10.11.6-MariaDB-0+deb12u1-log source revision  as process 11956
2024-07-29  9:25:38 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
2024-07-29  9:25:38 0 [Note] InnoDB: Number of transaction pools: 1
2024-07-29  9:25:38 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2024-07-29  9:25:38 0 [Note] InnoDB: Using liburing
2024-07-29  9:25:38 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2024-07-29  9:25:38 0 [Note] InnoDB: Completed initialization of buffer pool
2024-07-29  9:25:38 0 [Note] InnoDB: Buffered log writes (block size=512 bytes)
2024-07-29  9:25:38 0 [Note] InnoDB: End of log at LSN=46980
2024-07-29  9:25:38 0 [Note] InnoDB: 128 rollback segments are active.
2024-07-29  9:25:38 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2024-07-29  9:25:38 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2024-07-29  9:25:38 0 [Note] InnoDB: log sequence number 46980; transaction id 14
2024-07-29  9:25:38 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-07-29  9:25:38 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2024-07-29  9:25:38 0 [Note] InnoDB: Buffer pool(s) load completed at 240729  9:25:38
2024-07-29  9:25:38 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2024-07-29  9:25:38 0 [Note] Server socket created on IP: '127.0.0.1'.
2024-07-29  9:25:38 0 [Note] /usr/sbin/mariadbd: ready for connections.
Version: '10.11.6-MariaDB-0+deb12u1-log'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 12
mariadbd: pthread_mutex_lock.c:450: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
240729  9:26:56 [ERROR] mysqld got signal 6 ;
Sorry, we probably made a mistake, and this is a bug.

Your assistance in bug reporting will enable us to fix this for the next release.
To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.
```

```
mariadbd: pthread_mutex_lock.c:450: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
```
にかかれているように `Assertion` でクラッシュしているようです。

### Expected behavior

再現手順を実施して Mroonga がクラッシュしないこと。

### Environment

- OS: Debian 12
- OS Version: Debian 12
- DB: MariaDB 
- DB Version: 10.11.6-MariaDB
- Mroonga Version: 14.04
  - https://mroonga.org/docs/reference/server_variables.html#mroonga-version
- libgroonga Version: 14.0.6
  - https://mroonga.org/docs/reference/server_variables.html#mroonga-libgroonga-version

**Comment by Watson1978** [comment]
以下のように `user` テーブルの `id` から `AUTO_INCREMENT` を取り除くと、別のクラッシュが起きるようです。

```sql
CREATE TABLE user
(
    id          BIGINT         NOT NULL,
    name        VARCHAR(255)   NOT NULL,
    age         INTEGER        NOT NULL,
    FULLTEXT INDEX (name)
) ENGINE = Mroonga DEFAULT CHARSET utf8;
```

## 再現コード
```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'mysql2'
  gem 'faker'
end

class Initializer
  MAX_DATA = 10000

  def run
    drop_table
    create_table
    insert_initial_data
  end

  def drop_table
    client.query("DROP TABLE IF EXISTS user;")
  end

  def create_table
    client.query(<<~SQL)
      CREATE TABLE user
      (
          id          BIGINT         NOT NULL,
          name        VARCHAR(255)   NOT NULL,
          age         INTEGER        NOT NULL,
          FULLTEXT INDEX (name)
      ) ENGINE = Mroonga DEFAULT CHARSET utf8;
    SQL
  end

  def insert_initial_data
    sql = "INSERT INTO user VALUES"

    MAX_DATA.times do |i|
      sql << "(#{i+1}, \"#{client.escape(Faker::Name.name)}\", #{Random.rand(80)})"
      unless i == MAX_DATA - 1
        sql << ", "
      end
    end
    sql << ";"

    client.query(sql)
  end

  def client
    @client ||= Mysql2::Client.new(
      host: "localhost",
      username: "root",
      database: "test",
    )
  end
end

class Updater
  def initialize
    @record_count = Initializer::MAX_DATA
  end

  def run
    update
    insert
    flush
  end

  def update
    sql = "UPDATE user SET name = \"#{client.escape(Faker::Name.name)}\", age = #{Random.rand(80)} WHERE id = #{Random.rand(record_count)};"
    client.query(sql)
  end

  def insert
    id = record_count + 1
    sql = "INSERT INTO user (id, name, age) VALUES(#{id}, \"#{client.escape(Faker::Name.name)}\", #{Random.rand(80)});"
    client.query(sql)
  end

  def flush
    client.query("FLUSH TABLES;")
  end

  def record_count
    results = client.query("SELECT count(id) FROM user;")
    results.each do |row|
      return row["count(id)"]
    end
  end

  def client
    @client ||= Mysql2::Client.new(
      host: "localhost",
      username: "root",
      database: "test",
    )
  end
end

class Selecter
  def run
    results = client.query("SELECT * FROM user WHERE MATCH(name) AGAINST(\"+Mrs\" IN BOOLEAN MODE);")
    # results.each do |row|
    #   p row
    # end
  end

  def client
    @client ||= Mysql2::Client.new(
      host: "localhost",
      username: "root",
      database: "test",
    )
  end
end

Initializer.new.run

Thread.new do
  updater = Updater.new
  loop do
    updater.run
  end
end

Thread.new do
  selecter = Selecter.new
  loop do
    selecter.run
  end
end

sleep 120
```

## 結果
/var/log/mysql/mariadb_error.log には以下のようなログが出力されており、`_ZN10ha_mroonga5closeEv` (ha_mroonga の close) あたりでクラッシュが引き起こされているようでした。

```
2024-07-30  6:00:20 0 [Note] /usr/sbin/mariadbd: ready for connections.
Version: '10.11.6-MariaDB-0+deb12u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 12
free(): invalid next size (fast)
240730  6:03:35 [ERROR] mysqld got signal 6 ;
Sorry, we probably made a mistake, and this is a bug.

Your assistance in bug reporting will enable us to fix this for the next release.
To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Server version: 10.11.6-MariaDB-0+deb12u1 source revision:
key_buffer_size=134217728
read_buffer_size=131072
max_used_connections=3
max_threads=153
thread_count=3
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 468057 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x7155f4000c68
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x71563c07ec78 thread_stack 0x49000
/usr/sbin/mariadbd(my_print_stacktrace+0x2e)[0x5b88bc88226e]
/usr/sbin/mariadbd(handle_fatal_signal+0x2b3)[0x5b88bc3f2593]
/lib/x86_64-linux-gnu/libc.so.6(+0x3c050)[0x71566245b050]
/lib/x86_64-linux-gnu/libc.so.6(+0x8ae2c)[0x7156624a9e2c]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x12)[0x71566245afb2]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x715662445472]
/lib/x86_64-linux-gnu/libc.so.6(+0x7f430)[0x71566249e430]
/lib/x86_64-linux-gnu/libc.so.6(+0x947aa)[0x7156624b37aa]
/lib/x86_64-linux-gnu/libc.so.6(+0x9661a)[0x7156624b561a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_free+0x6f)[0x7156624b7e8f]
/usr/lib/mysql/plugin/ha_mroonga.so(_ZN10ha_mroonga5closeEv+0x184)[0x7156602b5234]
/usr/sbin/mariadbd(_Z8closefrmP5TABLE+0x119)[0x5b88bc29b0c9]
/usr/sbin/mariadbd(_Z8tc_purgev+0x61)[0x5b88bc37a211]
/usr/sbin/mariadbd(_Z12purge_tablesv+0xe)[0x5b88bc14afce]
/usr/sbin/mariadbd(_Z19close_cached_tablesP3THDP10TABLE_LISTbm+0x210)[0x5b88bc14e5f0]
/usr/sbin/mariadbd(_Z20reload_acl_and_cacheP3THDyP10TABLE_LISTPi+0x3f8)[0x5b88bc2efec8]
/usr/sbin/mariadbd(_Z21mysql_execute_commandP3THDb+0x1777)[0x5b88bc1b9207]
/usr/sbin/mariadbd(_Z11mysql_parseP3THDPcjP12Parser_state+0x1b5)[0x5b88bc1bcd05]
/usr/sbin/mariadbd(_Z16dispatch_command19enum_server_commandP3THDPcjb+0x1005)[0x5b88bc1bec35]
/usr/sbin/mariadbd(_Z10do_commandP3THDb+0x137)[0x5b88bc1c0247]
/usr/sbin/mariadbd(_Z24do_handle_one_connectionP7CONNECTb+0x3b7)[0x5b88bc2d3bf7]
/usr/sbin/mariadbd(handle_one_connection+0x5d)[0x5b88bc2d3f8d]
/usr/sbin/mariadbd(+0xc2f440)[0x5b88bc5ed440]
/lib/x86_64-linux-gnu/libc.so.6(+0x89134)[0x7156624a8134]
/lib/x86_64-linux-gnu/libc.so.6(+0x1097dc)[0x7156625287dc]

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (0x7155f4010cb0): FLUSH TABLES

Connection ID (thread ID): 35
Status: NOT_KILLED

Optimizer switch: index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,index_merge_sort_intersection=off,engine_condition_pushdown=off,index_condition_pushdown=on,derived_merge=on,derived_with_keys=on,firstmatch=on,loosescan=on,materialization=on,in_to_exists=on,semijoin=on,partial_match_rowid_merge=on,partial_match_table_scan=on,subquery_cache=on,mrr=off,mrr_cost_based=off,mrr_sort_keys=off,outer_join_with_cache=on,semijoin_with_cache=on,join_cache_incremental=on,join_cache_hashed=on,join_cache_bka=on,optimize_join_buffer_size=on,table_elimination=on,extended_keys=on,exists_to_in=on,orderby_uses_equalities=on,condition_pushdown_for_derived=on,split_materialized=on,condition_pushdown_for_subquery=on,rowid_filter=on,condition_pushdown_from_having=on,not_null_range_scan=off,hash_join_cardinality=off,cset_narrowing=off

The manual page at https://mariadb.com/kb/en/how-to-produce-a-full-stack-trace-for-mariadbd/ contains
information that should help you find out what is causing the crash.
Writing a core file...
Working directory at /var/lib/mysql
Resource Limits:
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        unlimited            unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             unlimited            unlimited            processes
Max open files            32768                32768                files
Max locked memory         524288               524288               bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       256148               256148               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
Core pattern: |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h

Kernel version: Linux version 6.9.10-1-MANJARO (builduser@fv-az1386-904) (gcc (GCC) 14.1.1 20240522, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT_DYNAMIC Fri Jul 19 15:08:51 UTC 2024
```
